platform: linux/arm

clone:
  clone:
    image: plugins/git:linux-arm
    tags: true

pipeline:
  docker:
    image: plugins/docker
    repo: shocki/dietzitrack
    tags: latest
    auto_tag: true
    secrets: [ docker_username, docker_password ]
    