platform: linux/arm

clone:
  default:
    image: plugins/git:linux-arm
    tags: true

pipeline:
  docker:
    image: shocki/dietzitrack
    tags: latest
    auto_tag: true
    secrets: [ docker_username, docker_password ]